### ISSUE TITLE
Exceptions for autocomplete and building

### ISSUE THREAD

**Issue by linuxrider** [equiva1ence/simple_ConTeXt#2]
I'm writing my thesis using context. Texmaker and gedit for editing.
Now I wanted to give your plugin a try.

I have 3 computers basically running the same setup, Ubuntu 17.04, texlive 2017 and sublime text 3 b3126 with simple_context 0.45.
The problem is that it only runs on one of the machines and I absolutely don't know what
the cause is.
Maybe you could help debugging this issue?
I tried a fresh install but it gives the same result (deleted sublime text config folder).
I also copied the config dir from the working computer to the other and still get the error messages shown below.
I'm have no experience using sublime text.
How could I collect more detailed debugging info?

This is what I get when typing a backslash:

in file "i-common-definitions.xml", error "[Errno 2] No such file or directory: "resolvers       | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml""
in file "i-common-definitions.xml", error "[Errno 2] No such file or directory: "resolvers       | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml""
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "completions in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 147, in reload_settings_aux
  File "completions in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 153, in save_interface
  File "scripts.save in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 35, in save
  File "scripts.save in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 98, in load_commands
FileNotFoundError: [Errno 2] No such file or directory: "resolvers       | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv"

Come up when trying to build a minimal example:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "build in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 119, in <lambda>
  File "build in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 164, in start_run_aux
  File "build in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 318, in add_result_to_output
ValueError: invalid literal for int() with base 10: 'resolvers'

Minimal example:
\starttext
\section[]{Test}
Test
\stoptext

The settings file working on one of the machines but not on the others.
{  
	"paths":
  	{
    "texlive": "/usr/local/texlive/2017/bin/x86_64-linux"
  	},
	"settings":
	{
		"PDF":
		{
			"viewer": "okular"
		},
		"builder":
		{
			"check":
			{
				"check_syntax_before_build": true,
				"stop_build_if_check_fails": true
			},
			"open_PDF_after_build": true,
			"program":
			{
				"name": "context",
				"options":
				{
					"arrange": false,
					"auto_pdf": false,
					"autogenerate": true,
					"interface": "en",
					"jit": false,
					"jiton": false,
					"mode":
					{
						"draft": false,
						"final": false
					},
					"paranoid": false,
					"runs": 9,
					"synctex": 1,
					"timing": false
				}
			},
			"show_errors_in_builder": true,
			"show_errors_in_main_view": true,
			"show_full_command_in_builder": true,
			"show_pages_shipped_in_builder": true,
			"show_path_in_builder": true,
			"show_warnings_in_builder": true
		},
		"path": "texlive",
		"pop_ups":
		{
			"line_break": 60,
			"on": true,
			"show_copy_pop_up": false,
			"show_source_files": false
		},
		"references":
		{
			"command_regex": "(in|at|about|[a-zA-Z]*ref)",
			"on": true,
			"reference_regex": "[a-zA-Z_\\.\\-\\:]*[_\\.\\-\\:]+[a-zA-Z_\\.\\-\\:]*"
		}
	}
}

**Comment by equiva1ence** [comment]
Just had a quick look at this. I think I know what the problem is. For parsing the XML interface goodies, I currently assume that the file `i-common-definitions.xml` exists (which I *think* is a reasonable assumption), locate it with the call `mtxrun --script locate i-common-definitions.xml`, and use the result of that call verbatim as the location of `i-common-definitions.xml`. *So*, in the error message

    [Errno 2] No such file or directory: "resolvers | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml"

what's happened is we've looked for a file called

    "resolvers | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml"

instead of (what appears to be) the actual name

    "/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml"

which has understandably upset python.

So the *root* of the problem is that I assumed that `mtxrun --script locate ...` would return a filename as is

    <filename>

since that's what it seems to do on my machine. But two out of three times for you, it is instead returning

    resolvers | trees | analyzing 'home:texmf'<filename>

So it looks like it should be a relatively easy fix. Could you verify for me that my suspicion is correct? That:
  - the one time where simple_ConTeXt is working is when running `mtxrun --locate script i-common-definitions.xml` returns the filename as is, 
  - the two times where it has trouble is when running `mtxrun --locate script i-common-definitions.xml` returns the filename, but with the text `resolvers | trees | analyzing 'home:texmf'` prefixed.

**Comment by linuxrider** [comment]
Thank you for your quick answer. It pointed me to the cause of this issue.

`mtxrun --locate i-common-definitions.xml` gives 
`resolvers       | trees | analyzing 'home:texmf'/usr/local/texlive/2017/texmf-dist/tex/context/interface/mkiv/i-common-definitions.xml`
for the non working install and only the filename for the working one. 
`mtxrun --locate --verbose i-common-definitions.xml` pointed at the reason:

 working 
```resolvers       | resolving | locating list of 'home:texmf' (runtime) (tree:///home:texmf)
resolvers       | resolving | locating list of 'home:texmf' (runtime) (tree:///home:texmf)
resolvers       | methods | resolving, method 'locators', how 'uri', handler 'tree', argument 'tree:///home:texmf'
resolvers       | trees | locator 'home:texmf' not found
```

 not working
```
resolvers       | resolving | locating list of 'home:texmf' (runtime) (tree:///home:texmf)
resolvers       | methods | resolving, method 'locators', how 'uri', handler 'tree', argument 'tree:///home:texmf'
resolvers       | trees | locator '/home/jo/texmf' found
resolvers       | resolving | hash 'home:texmf' appended
```

The existence of a texmf folder in my home dir changed the output of the locate command.
Maybe you could confirm that an empty texmf folder triggers the change in the output for
the locate command.

**Comment by equiva1ence** [comment]
Just tested, and yes I get the same behaviour: the existence of a folder `~/texmf` changes the output of the locate command. And this causes simple_ConTeXt to get stuck exactly as you reported.

At the python end, the relevant function is called `locate` in the file `scripts/utilities.py`. So I'll add some double-checking of the output to handle this situation, and then put up a new release. I wonder if this is the only unexpected thing that can happen with `mtxrun --locate ...`, or if there are others... for the moment, I'll just handle this specific case, as it's the only one I know of. (I tried having a look through `mtxrun` for clues, but it's such a massive file that I couldn't get to the bottom of it.)

Thanks @linuxrider for the excellent detective work!

**Comment by equiva1ence** [comment]
@linuxrider So I've put out a new release (v0.5.0) in which, among other things, I put in a patch for the python `locate` function mentioned above. It fixes the issue, as far as I can tell, on my machine. Does the issue persist for you?

**Comment by linuxrider** [comment]
@equiva1ence I've recreated the folder and it still works for me. Thanks.
