### ISSUE TITLE
command completion popup only shows up for certain parts

### ISSUE THREAD

**Issue by linuxrider** [equiva1ence/simple_ConTeXt#3]
The command completion pop-up only shows up when a certian part is finished.
\start... \stop... \setup... etc.
Unfortunately could not upload the screen cast.
Found the following exception in the console window.
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 191, in create_window_commands
    cmds.append(class_(window))
  File "build_context in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 35, in __init__
  File "build_context in /home/jo/.config/sublime-text-3/Installed Packages/simple_ConTeXt.sublime-package", line 42, in reload_settings
AttributeError: 'SimpleContextBuildContextCommand' object has no attribute '_base_input'
```

Or could this be a missconfiguration?
```

{
	"paths":
	{
		"texlive": "/usr/local/texlive/2017/bin/x86_64-linux"
	},
	"settings":
	{
		"PDF":
		{
			"viewer": "okular"
		},
		"builder":
		{
			"check":
			{
				"check_syntax_before_build": true,
				"stop_build_if_check_fails": true
			},
			"open_PDF_after_build": true,
			"program":
			{
				"name": "context",
				"options":
				{
					"arrange": false,
					"auto_pdf": false,
					"autogenerate": true,
					"interface": "en",
					"jit": false,
					"jiton": false,
					"mode":
					{
						"draft": false,
						"final": false
					},
					"paranoid": false,
					"runs": 9,
					"synctex": 1,
					"timing": false
				}
			},
			"show_errors_in_builder": true,
			"show_errors_in_main_view": true,
			"show_full_command_in_builder": true,
			"show_pages_shipped_in_builder": true,
			"show_path_in_builder": true,
			"show_warnings_in_builder": true
		},
		"path": "texlive",
		"pop_ups":
		{
			"line_break": 60,
			"on": true,
			"show_copy_pop_up": true,
			"show_source_files": true
		},
		"references":
		{
			"command_regex": "(in|at|about|[a-zA-Z]*ref)",
			"on": true,
			"reference_regex": "[a-zA-Z_\\.\\-\\:]*[_\\.\\-\\:]+[a-zA-Z_\\.\\-\\:]*"
		}
	}
}
```

**Comment by equiva1ence** [comment]
I believe this should be resolved in some of the unreleased commits. I'll put up a new release, which should fix the issue.

**Comment by linuxrider** [comment]
The gif shows the behaviour. There is no command suggestions.
Only possible paramaters for complete commands show up.
![out](https://user-images.githubusercontent.com/5882359/29805729-c4c130d4-8c8b-11e7-8524-0ac64a7e1953.gif)

**Comment by equiva1ence** [comment]
Ah, sorry for the misunderstanding. You want typing a backslash <kbd>\\</kbd> to bring up the list of commands, right?

I mention that in the readme [here](https://github.com/equiva1ence/simple_ConTeXt#general). That's the approach I've taken at the moment: you have to add an entry under `auto_complete_triggers` in the general Sublime Text settings, like so:

```JSON
{
  "auto_complete_triggers": [
    {
      "characters": "\\",
      "selector": "text.tex.context"
    }
  ]
}
```

This was the best approach that I could find, to allow for the ConTeXt completions to play nice with the other Sublime Text completions (e.g. using words in the current view, and snippets).

I don't know if there's a way to make that change automatically, and if so, whether this package *should* do something like that. Something to look into, it would be nice for it to be done automatically.

**Comment by linuxrider** [comment]
Right. Sorry I missed that part. Thought that it should work out of the box because it's already working in the first gif animation.

**Comment by equiva1ence** [comment]
Haha, no worries, I suppose it is a bit misleading. I'll see if I can set it up automatically in a future version.
